### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by OM4X** [dev7355608/advanced-drawing-tools#1]
Maybe a feature to lock the polygon to grid, so you can just fill the hexagons/squares with the color

**Comment by dev7355608** [comment]
I'm not sure I get the full picture: could you explain this in a bit more detail?

**Comment by Cubius** [comment]
Much in the same vein, I'd love to see grid snap for polygons, circles, and rectangles like implemented in [The Furnace](https://github.com/League-of-Foundry-Developers/fvtt-module-furnace). With the exception of text outlines via [Better Text Drawings](https://foundryvtt.com/packages/better-text-drawings), those features sadly never got picked up in another module.

**Comment by dev7355608** [comment]
Drawings are snapped though: so I assume you want a more aggressive snapping like with templates for example?

**Comment by Cubius** [comment]
Yes, [The Furnace ](https://github.com/League-of-Foundry-Developers/fvtt-module-furnace) used that same half grid snapping templates use, it was a very handy QOL feature for quickly drawing some clean grid-aligned shapes.

**Comment by dev7355608** [comment]
I added the *Force Snap To Grip* toggle to the drawings layer controls in v1.1.0.
