### ISSUE TITLE
[Request] Easily swap to 6-8 pre-defined colors.

### ISSUE THREAD

**Issue by gohma231** [dev7355608/advanced-drawing-tools#10]
I'm hoping that a quick color-swapper can be added to this module. 

When I run a game in-person. I have a wet-erase mat with 6-8 markers. I'm looking for the online equivalent. 

Owlbear.rodeo has a color picker and draw tools that work flawlessly for me. Here is a screenshot with their color picker:
![image](https://user-images.githubusercontent.com/4106435/227741092-47624b6f-d649-4939-be04-be363611c159.png)

**Comment by dev7355608** [comment]
This is probably a better fit for the *Precise Drawing Tools* module, which focuses on making the drawings tools actually work well for drawing.

**Comment by dev7355608** [comment]
This module is in maintenance only. I currently don't plan to add new features, because I don't have the time.
