### ISSUE TITLE
Text looks Visible on Arc

### ISSUE THREAD

**Issue by IronWarjack** [dev7355608/advanced-drawing-tools#11]
Foundry text takes on a visible appearance when used with Arc.  This makes it hard to know which text IS actually visible. I have toggled the visibility on/off without change. Currently using most recent version of Foundry and Module.

None of the text in this image is visible: https://i.imgur.com/f2cTp7j.jpg
Only the green in this image is visible: https://i.imgur.com/SgmxtI5.png

**Comment by dev7355608** [comment]
Thanks for the report! Fixed it.
