### ISSUE TITLE
Don't gobble up leading whitespace

### ISSUE THREAD

**Issue by yorkshirelandscape** [dev7355608/advanced-drawing-tools#12]
Currently, text boxes will gobble up (i.e., not display) any leading whitespace. I presume this is Foundry doing this, but if you could override it, or provide the option to, that would be terrific. It's often necessary for aligning text just so.

**Comment by dev7355608** [comment]
The text is trimmed by Foundry, and there's no what to stop that (the text is trimmed on the server).

**Comment by yorkshirelandscape** [comment]
Bummer. Thanks for looking into it, though. Actually, I have since discovered a new favorite Unicode character called Braille Blank which, in most fonts, is rendered as an empty space but is not classed as whitespace. Consequently, you can use it to adjust spacing in situations like this.
