### ISSUE TITLE
Not active on FoundryVTT 11.302

### ISSUE THREAD

**Issue by paul-tergeist** [dev7355608/advanced-drawing-tools#13]
I have installed the Adv. Drawing Tools 2.0.11 and libWrapper 1.12.12.1 and no other modules; both modules are activated in a brand new world.

I don't see any extra tools in the walls tool. When I create a new empty scene and draw a wall, clicking on the wall to create a new node does nothing. Double clicking that wall opens up the wall parameters. Right clicking a node does not delete it.
It is as if the module were not installed at all.

any ideas/tipps?
![image](https://github.com/dev7355608/advanced-drawing-tools/assets/29351404/25300f39-acff-4ace-b52c-10b529f5cbff)

**Comment by dev7355608** [comment]
Advanced Drawing Tools doesn't include any features related to walls. Only drawings. The polygon in edit mode look similar to walls though. So I assume that's where the confusion comes from when you looked at the demo gif (?). There are modules out there that improve the walling tools. Monk's Wall Enhancement for example, which might just have the features you are looking for: splitting walls and dragging two connected wall endpoints at once.

**Comment by paul-tergeist** [comment]
oh, you're right of course - i was looking for monks wall enhancement :-/ i mixed those two up
