### ISSUE TITLE
Word Wrap broken

### ISSUE THREAD

**Issue by Cubius** [dev7355608/advanced-drawing-tools#14]
As per the title, word wrap appears to be broken as of Foundry v11.

The toggle to turn it on/off seems to be missing from the Drawing/Text configuration too.

**Comment by dev7355608** [comment]
Word Wrap Width seems to work fine here with the exception that it doesn't seem to update immediately. I removed the Word Wrap checkbox, because a large Word Wrap Width basically has the same effect.

**Comment by Cubius** [comment]
![image](https://github.com/dev7355608/advanced-drawing-tools/assets/15717384/f98e7304-cc7a-4c7a-bb17-42b723bc94c8)

Word Wrap Width seems to have no effect on drawings as far as I can tell.

Also it appears that the snap-to-grid drawing functionality is broken again.

Foundry v11.302

Advanced Drawing Tools 2.0.11

Find the Culprit to remove pretty much everything besides library modules:

![image](https://github.com/dev7355608/advanced-drawing-tools/assets/15717384/ea01b4b6-db57-4c4f-b208-1460cd1ea4f9)

**Comment by dev7355608** [comment]
Word breaking is not enabled and therefore words are not broken if the wrap width is exceeded. Lines are only wrapped on white space.

I did a quick test: grid snapping seems to work fine here.
