### ISSUE TITLE
Feature Request: Vertical Alignment

### ISSUE THREAD

**Issue by DariusWolfe** [dev7355608/advanced-drawing-tools#15]
I would like to be able to write a text blurb and not have it vertically centered in the text box. This currently causes a lot of manual adjustment of the text box, because if the text is too short, it shifts the whole blurb down to be centered in the box, and if it's too long, it shifts it up to overlap the text box. If I could set a vertical alignment, it would make things a lot simpler and cleaner.

**Comment by dev7355608** [comment]
This module is in maintenance only. I currently don't plan to add new features, because I don't have the time.
