### ISSUE TITLE
HUD button for lines/shapes to change the line/fill color (with lib colorpicker)

### ISSUE THREAD

**Issue by apoapostolov** [dev7355608/advanced-drawing-tools#3]
Changing color of drawings is very annoying as you have to open the settings dialog and dig into the huge amount of settings to find the line and fill colors. Adding buttons on the hud that use the current colors and on click, open colorpicker and allow to change the color without having to mess with settings dialog, would be greatly appreciated.

**Comment by dev7355608** [comment]
This is probably a better fit for the *Precise Drawing Tools* module, which focuses on making the drawings tools actually work well for drawing.

This module is in maintenance only. I currently don't plan to add new features, because I don't have the time.
