### ISSUE TITLE
Text Alignment doesn't work

### ISSUE THREAD

**Issue by YuanRamirez** [dev7355608/advanced-drawing-tools#5]
Tested in both v9 and v10, with and without other modules. Text alignment just doesn't change anything about the way the text is displayed in the drawing.

The following is a text drawing with text alignment set to left.

![image](https://user-images.githubusercontent.com/24588007/195983022-7db33129-2fb9-479a-af1a-8dd697bf6c25.png)

**Comment by dev7355608** [comment]
Technically the text was left aligned, but the line width of the text isn't the same size as the width of the drawing and text itself is centered in the drawing shape. So it only had an effect for multiline text.

I changed this behavior in 2.0.4; now the text itself is positioned according to the text alignment.
