### ISSUE TITLE
Hide advanced text options

### ISSUE THREAD

**Issue by MarkovChainmail** [dev7355608/advanced-drawing-tools#6]
It's cool to have the advanced text options, but they make the text screen very cluttered, and most of the time the advanced text options aren't necessary for me. It'd be nice if they could be hidden.

**Comment by MarkovChainmail** [comment]
A dropdown menu might be nice

**Comment by dev7355608** [comment]
I don't think I will hide an option to the advanced options. But it might become simpler to organize the advanced options in a better way with the config improvements (Application V2) in V13.
