### ISSUE TITLE
MAT alter function removes Font and advanced drawing colors

### ISSUE THREAD

**Issue by Vralek** [dev7355608/advanced-drawing-tools#8]
I made a Monks Active tile that Alters the coloration of a drawing on mouse over both in and out functions.
However, when it changes, it removes the font and the advanced drawing tools colorations, which I love.

The monks active tile function works as expected, except for the coloration dropping. This happened a few months ago and I hoped an update from ADT would have fixed it but it's still an issue.

Tile setup: 
https://imgur.com/6nwNTMg
https://imgur.com/VbvvTiu
Issue:
https://imgur.com/oSRG3s5

**Comment by dev7355608** [comment]
Technically not a bug, because `flags.advanced-drawing-tools.fill` is supposed to be an array. MATT doesn't seems to be able to set array values. But I made a change that should allow it to work now.

**Comment by Vralek** [comment]
Can confirm that this did resolve the issue. Thanks!

**Comment by Vralek** [comment]
Fixed result: https://i.imgur.com/PG73eL6.gif
