### ISSUE TITLE
Justifed alignment not working

### ISSUE THREAD

**Issue by yorkshirelandscape** [dev7355608/advanced-drawing-tools#9]
Justified text is showing up as left-aligned.

Foundry 10.291
Pathfinder 2e 4.9.3
Advanced Drawing Tools 2.0.6

<img width="489" alt="justify" src="https://user-images.githubusercontent.com/1088016/226586818-05297098-3aed-478c-82fb-04f31b95700c.png">

**Comment by dev7355608** [comment]
While it is documented to be a valid option for PIXI text styles, it doesn't actually do anything: justify support hasn't been implemented and behaves just like left alignment. I'm going to remove this option in the next update.
